// <auto-generated />
namespace LMS_Lexicon2015.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ökat_fältlängd_för_beskrivningsfält_till_3000tkn_i_modelerna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ökat_fältlängd_för_beskrivningsfält_till_3000tkn_i_modelerna));
        
        string IMigrationMetadata.Id
        {
            get { return "201512091047284_ökat_fältlängd_för_beskrivningsfält_till_3000tkn_i_modelerna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
