// <auto-generated />
namespace LMS_Lexicon2015.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Required2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Required2));
        
        string IMigrationMetadata.Id
        {
            get { return "201512041545319_Required2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
