// <auto-generated />
namespace LMS_Lexicon2015.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Ökat_fältlängd_för_beskrivning_i_fler_modeller : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ökat_fältlängd_för_beskrivning_i_fler_modeller));
        
        string IMigrationMetadata.Id
        {
            get { return "201512091042364_Ökat_fältlängd_för_beskrivning_i_fler_modeller"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
